[package]
name = "serde-ndim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = { version = "0.32.2", default-features = false, optional = true }
ndarray = { version = "0.15.6", default-features = false, optional = true }
serde = "1.0.159"
