name: Rust

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: cargo test --verbose
    - name: Add no_std target
      run: rustup target add thumbv7m-none-eabi
    - name: Verify no_std build
      run: cargo check --no-default-features --target thumbv7m-none-eabi --verbose
